# Generated by Claude on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_loginhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmember",
            name="social_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kakao", "카카오"),
                    ("naver", "네이버"),
                    ("google", "구글"),
                    ("apple", "애플"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stockmember",
            name="social_uid",
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name="stockmember",
            name="social_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="stockmember",
            name="social_linked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="stockmember",
            unique_together={("social_provider", "social_uid")},
        ),
    ]
