# Generated by Django 4.1.13 on 2026-07-22 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stockmember_social_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('is_required', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('enacted_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='MemberConsentAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(db_index=True, max_length=40)),
                ('item_key', models.SlugField(max_length=60)),
                ('version', models.PositiveIntegerField()),
                ('agreed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-agreed_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentItemRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('title_ko', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('body_ko', models.TextField()),
                ('body_en', models.TextField()),
                ('change_summary', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(blank=True, max_length=80)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='stock.consentitem')),
            ],
            options={
                'ordering': ['item', '-version'],
                'unique_together': {('item', 'version')},
            },
        ),
    ]
