# Generated by Django 6.0.6 on 2026-07-22 09:57

import django.db.models.deletion
from datetime import datetime, timezone
from django.db import migrations, models


def seed_context_content(apps, schema_editor):
    MarketEvent = apps.get_model("stock", "MarketEvent")
    samples = [
        ("005930.KS", "earnings", "다음 실적 발표 일정 확인", "Samsung Electronics IR", "https://www.samsung.com/global/ir/", datetime(2026, 10, 1, tzinfo=timezone.utc)),
        ("AAPL", "earnings", "다음 실적 발표 일정 확인", "Apple Investor Relations", "https://investor.apple.com/", datetime(2026, 10, 1, tzinfo=timezone.utc)),
        ("MSFT", "dividend", "다음 배당 일정 확인", "Microsoft Investor Relations", "https://www.microsoft.com/en-us/Investor", datetime(2026, 9, 1, tzinfo=timezone.utc)),
    ]
    for symbol, kind, title, source, url, at in samples:
        MarketEvent.objects.get_or_create(symbol=symbol, event_type=kind, title=title, defaults={"event_at":at,"source_name":source,"source_url":url,"is_estimated":True})


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_consentitem_memberconsentagreement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataQualityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(blank=True, max_length=30)),
                (
                    "provider",
                    models.CharField(
                        default="Yahoo Finance via yfinance", max_length=80
                    ),
                ),
                ("status", models.CharField(default="success", max_length=20)),
                ("is_delayed", models.BooleanField(default=True)),
                ("reference_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MarketEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=30)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("earnings", "실적 발표"),
                            ("dividend", "배당"),
                            ("meeting", "주주총회"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("event_at", models.DateTimeField()),
                ("source_name", models.CharField(max_length=120)),
                ("source_url", models.URLField()),
                ("is_estimated", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="StockNewsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=30)),
                ("title", models.CharField(max_length=240)),
                ("source_name", models.CharField(max_length=120)),
                ("source_url", models.URLField()),
                ("published_at", models.DateTimeField()),
                ("fact_summary", models.TextField()),
                ("market_interpretation", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="PriceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=30)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("above", "가격 이상"),
                            ("below", "가격 이하"),
                            ("change_up", "등락률 이상"),
                            ("change_down", "등락률 이하"),
                        ],
                        max_length=20,
                    ),
                ),
                ("threshold", models.DecimalField(decimal_places=4, max_digits=18)),
                ("is_active", models.BooleanField(default=True)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_alerts",
                        to="stock.stockmember",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecentlyViewedStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=30)),
                ("viewed_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recent_stocks",
                        to="stock.stockmember",
                    ),
                ),
            ],
            options={
                "ordering": ["-viewed_at"],
                "unique_together": {("member", "symbol")},
            },
        ),
        migrations.CreateModel(
            name="WatchlistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=30)),
                ("display_name", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchlist",
                        to="stock.stockmember",
                    ),
                ),
            ],
            options={
                "unique_together": {("member", "symbol")},
            },
        ),
        migrations.RunPython(seed_context_content, migrations.RunPython.noop),
    ]
